export default {
  'en': {
    'sender': 'Sender',
    'session_date': 'Session date',
    'session_time': 'Session time',
    'msg': 'Message',
    'new_videos': 'New videos and photos from ultrasound session are available on',
    'new_videos2': '',
    'please_use': 'Please use your email address as your login id',
    'your_pass': 'Your password is',
  },
  'de': {
    'sender': 'Absender',
    'session_date': 'Sitzungsdatum',
    'session_time': 'Sitzungszeit',
    'msg': 'Botschaft',
    'new_videos': 'Neue Videos und Fotos von der Ultraschallsitzung sind auf',
    'new_videos2': 'verfügbar',
    'please_use': 'Bitte verwenden Sie Ihre E-Mail-Adresse als Login-ID',
    'your_pass': 'Ihr Passwort lautet',
  },
  'ko': {
    'sender': '송신기',
    'session_date': '세션 날짜',
    'session_time': '세션 시간',
    'msg': '메시지',
    'new_videos': '초음파 세션의 새로운 비디오 및 사진은',
    'new_videos2': '에서 볼 수 있습니다',
    'please_use': '이메일 주소를 로그인 ID로 사용하십시오',
    'your_pass': '귀하의 비밀번호',
  },
  'ja': {
    'sender': '送信者',
    'session_date': 'セッション日',
    'session_time': 'セッション時間',
    'msg': 'メッセージ',
    'new_videos': '超音波セッションからの新しい動画や写真は',
    'new_videos2': 'で入手できます',
    'please_use': 'あなたのログインIDとしてあなたの電子メールアドレスを使用してください',
    'your_pass': 'あなたのパスワードは',
  },
  'zh': {
    'sender': '寄件人',
    'session_date': '会议日期',
    'session_time': '会议时间',
    'msg': '信息',
    'new_videos': '超声会议的新视频和照片可在',
    'new_videos2': '上找到',
    'please_use': '请使用您的电子邮件地址作为您的登录ID',
    'your_pass': '您的密码是',
  },
  'es': {
    'sender': 'Remitente',
    'session_date': 'Fecha de la sesión',
    'session_time': 'Tiempo de sesión',
    'msg': 'Mensaje',
    'new_videos': 'Los nuevos videos y fotos de la sesión de ultrasonido están disponibles en',
    'new_videos2': '',
    'please_use': 'Por favor, use su dirección de correo electrónico como su ID de inicio de sesión',
    'your_pass': 'Tu contraseña es',
  },
  'pt': {
    'sender': 'Remetente',
    'session_date': 'Data da sessão',
    'session_time': 'Tempo de sessão',
    'msg': 'Mensagem',
    'new_videos': 'Novos vídeos e fotos da sessão de ultra-som estão disponíveis em',
    'new_videos2': '',
    'please_use': 'Por favor, use seu endereço de e-mail como seu ID de login',
    'your_pass': 'Sua senha é',
  },
  'fr': {
    'sender': 'Expéditeur',
    'session_date': 'Date de session',
    'session_time': 'Temps de session',
    'msg': 'Message',
    'new_videos': 'De nouvelles vidéos et photos de la séance d’échographie sont disponibles sur',
    'new_videos2': '',
    'please_use': 'Veuillez utiliser votre adresse e-mail comme identifiant de connexion',
    'your_pass': 'Votre mot de passe est',
  },
  'it': {
    'sender': 'Mittente',
    'session_date': 'Data della sessione',
    'session_time': 'Tempo di sessione',
    'msg': 'Messaggio',
    'new_videos': 'Nuovi video e foto dalla sessione ad ultrasuoni sono disponibili su',
    'new_videos2': '',
    'please_use': 'Si prega di utilizzare il tuo indirizzo email come ID di accesso',
    'your_pass': 'La tua password è',
  },
  'ru': {
    'sender': 'Отправитель',
    'session_date': 'Дата сессии',
    'session_time': 'Время сессии',
    'msg': 'Сообщение',
    'new_videos': 'Новые видео и фотографии с ультразвукового сеанса доступны на',
    'new_videos2': '',
    'please_use': 'Пожалуйста, используйте свой адрес электронной почты в качестве идентификатора входа',
    'your_pass': 'Ваш пароль',
  },
}
